language: python

matrix:
  include:
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

cache: pip3

before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_cebf25e6c525_key
  -iv $encrypted_cebf25e6c525_iv -in .env.enc -out .env -d || true'
- npm install npm@latest -g

install:
- pip3 install tox-travis

before_script:
- pip3 install -r requirements.txt
- pip3 install -r requirements-dev.txt
- pip3 install --editable .

script:
- pip3 install -U python-dotenv
- tox

before_deploy:
- sudo apt-get update
- pip3 install pypandoc
- sudo apt-get install pandoc
- pip3 install bumpversion
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

deploy:
- provider: script
  script: docs/publish.sh
  skip_cleanup: true
  on:
    python: '3.5'
    tags: true
- provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    python: '3.5'
    branch: master
- provider: pypi
  user: watson-devex
  password: $PYPI_PASSWORD
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.5'
    tags: true
