language: python
sudo: false

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

cache: pip

before_install:
- openssl aes-256-cbc -K $encrypted_6e98b3e8e789_key -iv $encrypted_6e98b3e8e789_iv
  -in .env.enc -out .env -d

install: pip install tox-travis
script: tox

after_success:
- codecov
- docs/publish.sh
