environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: py38

install:

  # Install Tox
  - pip install tox==3.23.0

build: off

test_script:
  - tox

deploy: off

matrix:
  fast_finish: true